name: UI Python Playwright

on:
  push:
    branches:
      [master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps
      - name: Run tests with allure files generation
        run: pytest --browser=${{ matrix.browser }} --alluredir=reports/allure-reports
      - name: Install Allure
        run: npm install -g allure-commandline
      - name: Generate Allure report
        run: allure generate reports/allure-reports -o reports/allure-report --clean
      - name: Deploy Allure report to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/allure-report
          publish_branch: gh-pages
          keep_files: false